### PR TITLE
Add expire report and alert

### PR DESCRIPTION
**Pull request by marionbarker**
Current Status:
* Merged updates from Bill Gestrich
* Works for Mac-Xcode test but puzzled by difference with Loop
  * Compare expiration to Loop built right after LoopCaregiver (no change to mobile provisioning)
  * LoopCaregiver 359 days, Dec 7 2024 at 17:22
  * Loop 352 days, Nov 30 2024 at 16:24
* Works for TestFlight and agrees with what TestFlight reports
   * within error range - we add 90 days and sometimes TestFlight says expires in 91 days
   * LoopCaregiver says 89 days remaining, March 13, 2024 at 07:40 (now 08:00)
   * TestFlight says expires in 91 days
   * Advanced test phone time to March 14 and get "LoopCaregiver" Beta Has Expired
   * Changed test phone time to March 12 and get TestFlight Expires soon modal alert

For both Mac-Xcode and GitHub build, link goes to appropriate LoopDocs page.

Original Status:
Status
* Copied build information gathering code from Loop
* Copied TestFlight detection code from Loop
* Add an expiration section to SettingsView.swift

What happens now: 
* for xcode build, expiration date is 1 year from build date - but Loop uses actual profile expiration data
* for "fake" testflight (I hack a return true inside isTestFlightBuild) - buildDate is nil, so get "N/A" for expiration

### CODE REVIEW

**Comment by marionbarker** [comment]
At this time, these two files are duplicates from Loop
* LoopCaregiver/Scripts/capture-build-details.sh (with a few added info statements that can / should be removed)
* LoopCaregiver/LoopCaregiver/Models/BuildDetails.swift

Do we want to modify these files in Loop and LoopCaregiver to be more generic so the same file can be used for all the Open-Source apps?

**Comment by marionbarker** [comment]
Next test - remove provisioning profile on my Mac and build again.
* LoopCaregiver: 364 days remaining, Dec 13, 2024 at 08:16
* Loop: 364 days remaining, Dec 13, 2024 at 08:16

So evidently the provisioning profile in a given Xcode instance can be different from another one. I was building from clones that I was updating, not fresh clones.

**Review by gestrich — APPROVED** [review]

**Comment by gestrich** [comment]
@marionbarker  It sounds like this is ready to merge. Or let me know if there are still lingering concerns on your comments above.

**Comment by marionbarker** [comment]
After deleting all profiles, a new profile is only generated when Xcode is used to build the app.

I built LoopFollow slightly later in the day than LoopCaregiver and Loop; and the provisioning profile expiration was the same day, but slightly later, Dec 13, 2024 at 09:13 PST (17:13Z)

Today I deleted the single provisioning profile with that date and build LoopFollow again, it now shows provisioning profile will expire 2024-12-14T15:34:58Z.

Rebuilding LoopCaregiver from my local clone maintains the date in the previous comment.

**Comment by marionbarker** [comment]
This has been tested with Mac-Xcode build and TestFlight. The test phone time was advanced and demonstrated the appropriate behavior when near and after the TestFlight estimated expiration time. (Note that we use 90 days from build date and sometimes TestFlight gives a little more time. This is deemed good enough.)

Ready to merge.

**Pull request merged**
