### PR TITLE
Bump browser build dependencies to Node 20

### PR DESCRIPTION
**Pull request by dnzxy**
Bumping dependencies for browser build, see LoopKit/LoopWorkspace#120 for detailed description.

### CODE REVIEW

**Comment by gestrich** [comment]
@dnzxy Did you get a chance to test that Caregiver browser builds are still successful after this version update?

**Comment by dnzxy** [comment]
@gestrich In all transparency, no, I have not; but this has been merged in iAPS already and is in use there, and there is not a single thing that comes to mind that would break the fastlane build using updated checkout, sync and artifact actions. It is only necessary to confer to newer requirements by GitHub for the used NodeJS version in actions.

Let me spin up a browser build on my end and quickly verify it for completeness sake.

**Comment by marionbarker** [comment]
I tested using the loopdocs-tester GitHub organization where I do most of my browser build testing.
I created a parallel PR to loopdocs-tester to branch update, which worked.

But I see you already merged.

Here is my successful build. 
* https://github.com/loopdocs-tester/LoopCaregiver/actions/runs/8269095048

**Comment by gestrich** [comment]
@marionbarker Thanks for the verification!

**Pull request merged**
