### PR TITLE
Various browser build updates & fixes

### PR DESCRIPTION
**Pull request by dnzxy**
**Contents**
* Bump fastlane to 2.220.0
* Bump action container OS from `macos-12` and `macos-13` to `macos-14`
* Bump Xcode selection to latest stable 15.3 (15.4 still in beta; cf. [GitHub action runner-images macos-14 Readme](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode))

**Why this PR?**
Please see https://github.com/LoopKit/LoopWorkspace/pull/126

**Tests**
Tested by running all actions (in conjunction with previously having built another app that writes to the same `Match-Secrets` repository).
- Validate Secrets: https://github.com/dnzxy/LoopCaregiver/actions/runs/8913304089
- Add Identifiers: https://github.com/dnzxy/LoopCaregiver/actions/runs/8913317277
- Create Certificates: https://github.com/dnzxy/LoopCaregiver/actions/runs/8913333063
- Build LCG: https://github.com/dnzxy/LoopCaregiver/actions/runs/8913351392

### CODE REVIEW

**Comment by marionbarker** [comment]
I tested this modification as well. It works as expected and conforms with the updates we had to add to keep Loop main and dev building without Browser Build errors.

**Comment by marionbarker** [comment]
One comment regarding code inspection. 

When I create the PR to LoopWorkspace, I choose to delete the commented out lines in add_identifiers and create_certificate regarding Xcode version because they are not used; e.g. lines 17, 18 and 19 in those 2 yml files. 

The reference to Xcode version is already removed from validate_secrets.

**Comment by dnzxy** [comment]
> When I create the PR to LoopWorkspace, I choose to delete the commented out lines in add_identifiers and create_certificate regarding Xcode version because they are not used; e.g. lines 17, 18 and 19 in those 2 yml files.

When you do not select a specific Xcode version via `sudo xcode-select`, Xcode will use the default version that comes with the GitHub action runner image. For `macos-14` runners, this is `15.0.1`(see [here](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#xcode)). 

I chose to go with the highest available and stable Xcode version for the build action, but stick with using the default version for the other 3 actions. As you can see from my changes, I actually updated the commented out version to 15.3 as well. We can remove the commented out lines, or we can leave them in there.  I'm fine with either :)

**Comment by gestrich** [comment]
Just give me a holler when ready to merge.

**Comment by dnzxy** [comment]
It’s ready to merge. The commented in/out code is up to you. If you are okay with leaving it in the, you can merge. If you prefer to have it removed, I can quickly remove it, and it can be merged 😊

**Review by gestrich — APPROVED** [review]

**Pull request merged**
